//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_StoredProcedures_attr
    {
        public long AttrId { get; set; }
        public long TerminologyId { get; set; }
        public long CampaignId { get; set; }
        public string AttributeName { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string Datatype { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Terminology Terminology { get; set; }
    }
}
