//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_TestCampaign
    {
        public long Id { get; set; }
        public long CampaignId { get; set; }
        public long ConsumerId { get; set; }
        public string AssessmentNumber { get; set; }
        public string AssessmentAddress { get; set; }
        public string AssessmentNotice { get; set; }
    }
}
