//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorText
    {
        public int Id { get; set; }
        public Nullable<int> ColorId { get; set; }
        public string Text { get; set; }
    
        public virtual Color Color { get; set; }
    }
}
