//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumer()
        {
            this.ConsumerEmails = new HashSet<ConsumerEmail>();
            this.ConsumerReferences = new HashSet<ConsumerReference>();
            this.RegistrationLogs = new HashSet<RegistrationLog>();
        }
    
        public long Id { get; set; }
        public long UserCampaignMappingId { get; set; }
        public long CampaignId { get; set; }
        public bool ActiveFlag { get; set; }
        public Nullable<int> Consent { get; set; }
        public Nullable<System.DateTime> TandCAcceptedDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual ConsentMaster ConsentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerEmail> ConsumerEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerReference> ConsumerReferences { get; set; }
        public virtual UserCampaignMapping UserCampaignMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationLog> RegistrationLogs { get; set; }
    }
}
