//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerEmail
    {
        public long Id { get; set; }
        public long ConsumerId { get; set; }
        public string Email { get; set; }
        public bool ActiveFlag { get; set; }
        public bool IsPrimaryEMail { get; set; }
        public int EMailVerificationStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual EMailVerificationStatusMaster EMailVerificationStatusMaster { get; set; }
    }
}
