//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correspondence
    {
        public long Id { get; set; }
        public long ConsumerReferenceId { get; set; }
        public System.DateTime ConsumerCorrespondenceDate { get; set; }
        public decimal Balance { get; set; }
        public decimal BalanceDue { get; set; }
        public string SecurDocsReference { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual ConsumerReference ConsumerReference { get; set; }
    }
}
