//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationLog
    {
        public long Id { get; set; }
        public long ConsumerId { get; set; }
        public int RegistrationStatus { get; set; }
        public System.DateTime StatusChangeDate { get; set; }
        public string StatusChangedBy { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual RegistrationStatusMaster RegistrationStatusMaster { get; set; }
    }
}
