//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminology
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terminology()
        {
            this.Client_StoredProcedures_attr = new HashSet<Client_StoredProcedures_attr>();
            this.SPAttributes = new HashSet<SPAttribute>();
            this.TerminologiesDetails = new HashSet<TerminologiesDetail>();
        }
    
        public long Id { get; set; }
        public long CampaignId { get; set; }
        public int HTMLElementID { get; set; }
        public string TerminologyKey { get; set; }
        public string TerminologyText { get; set; }
        public string Description { get; set; }
        public bool Searchable { get; set; }
        public int SortOrder { get; set; }
        public bool isMandatory { get; set; }
        public Nullable<long> ValidationId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_StoredProcedures_attr> Client_StoredProcedures_attr { get; set; }
        public virtual HTMLMaster HTMLMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPAttribute> SPAttributes { get; set; }
        public virtual ValidationMaster ValidationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminologiesDetail> TerminologiesDetails { get; set; }
    }
}
