//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermsAndCondition
    {
        public long Id { get; set; }
        public long CampaignId { get; set; }
        public string TermsAndConditions { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
