//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerRegistrationPortal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminologiesDetail
    {
        public long Id { get; set; }
        public long TerminologiesId { get; set; }
        public string Value { get; set; }
        public int SortOrder { get; set; }
        public Nullable<bool> Selected { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string DisplayText { get; set; }
    
        public virtual Terminology Terminology { get; set; }
    }
}
